# Generated by Django 3.1 on 2020-09-05 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('venue', models.CharField(max_length=200)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('event_code', models.CharField(default='29U5S6', editable=False, max_length=6)),
                ('estimated_size', models.IntegerField(choices=[(1, '0 - 500+'), (2, '600 - 1000+'), (3, '1000 - 1500+')], default=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('user_code', models.CharField(default='PEQ896V8O5', editable=False, max_length=10)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('event_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.event')),
            ],
        ),
    ]
